Repository kubescape/k8s-interface, pull requests merged in 2024-02, with the labels that each got.

#91 Adding instance type
  instanceidhandler/interface.go
  instanceidhandler/v1/containerinstance/instanceidhandler.go
  instanceidhandler/v1/helpers/keys.go
  instanceidhandler/v1/initcontainerinstance/instanceidhandler.go
Labels: enhancement, Review effort [1-5]: 2

#92 Fixed parse eks region
  cloudsupport/v1/ekssupport.go
  cloudsupport/v1/ekssupport_test.go
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#93 bump deps, get rid of deprecated types.AuthConfig
  .github/workflows/pr.yaml
  .github/workflows/release.yaml
  cloudsupport/cloudvendorregistrycreds.go
  cloudsupport/dockerregistrycredsutils.go
  go.mod
  go.sum
Labels: enhancement, Review effort [1-5]: 2, dependencies
